language: android
jdk: oraclejdk8
sudo: false
addons:
  apt:
    packages:
    - lynx
android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.1
  - android-26
  - extra-android-m2repository
before_install: chmod +x gradle/buildWithTravis.sh
script: gradle/buildWithTravis.sh
env:
  global:
  - secure: ZlypzgkiOdfErh5F6YX4GpwG5yhbArOarwMbqAhdrkrr29hm8W37Dqi/Uve5wxkrofuY7c/3ycJu6Cn4lf3VUs9VmmjVdFqy9YHw8mBrHRG4vKdXs2IQwIv5tt2qGc1aBVWHdS7rOdpw6xPcm6uEo/eNcAyb8AkGC3LGseH5RAdzKx3Ag23u9JLOLAqi65ta22PanWb3Lbi1ZNA5DBjTaeR9R073v+NaCaMcCDcg++Bh/FLXnbJuzGObw41mQW6GCxnC48ly6/GLkZobk3J9lOIHXJh6cfmf8daSfH2Hjvn+RObblSiOLgQjJCFnFh8ywScLavLw0zSK5SgMWDRA7jh4ZpPvwnYKsSs5TOEWFfujwPtFLJw/TAXRW8DS8Qnlc3A8QUOdC/YvULSBgFiGpCJGLJs5cKHwTsU5rDYczB6Ouegs2ItCRFDLtW9FehXXzp2WRZlaTW7l4hh8yM0GnXkzEDlotQUaI10dTWeTJFormPwfWDufsSN3+OTTJceVg8PnfER19f31PCUtJ6SCDPTVbWcKzUx/8D1sptI+ouhcNGs8TRxkxRRKLssyRMoMGKKtX0rTkCdPdRy+oaYcRhzYsxG9AH6l5KoP92upyBapfPpLGYqPYdcfWyzKKfVIT532ElpKAb5kXLUpueyGj+kLylYZscYDnkWRE/7jA/M=
  - secure: K5dyTwG94gZYTmTf7HtSrYcvCGQIaydWTuBGZ4Iqr5O71fnjCzyf0PH2o8PunUTo6lIFwfkqRIbyQurQeBg7LV9aJiJl6z/loHJw90PnlxYtd15ZYiOatV4OQ+okCIRtpIj17oGFioxeLpYGLHCcZY3H2sy6kkmfyyHr+HWqfo1wfVwbDK7GDe0XyB3BvAA4o+fsT4WQ8pIdpgz2i0xNt77XWiQeRBMFHyM0bIouPbsiisCDk75ciIA5AZND31KmS7SMKvCUVHfUWJcqXIv3cq2jYf8NXcyvjFqztnO2eFMY2x7qzx1z6s4GGqLIOlup2Q2aH+bUi/qEhqFpmfKFAo81W96hdet7d6YrWXsz7L5tgfQx6TMgGnTzpGLmMuiOxrNlmFggkSfi4n8MzvrIj6y1ZgV/cRV2Ktq6PT8HM968cbuyMZhT5LuGPxRmOZFAjRrhrr0AO6hDDs7bnSCyXHUwjLR8qpLIEVCqmr3kwXZ6fVos5PU9OmEllRkNoRL6c2EIXZoenW0LhXAX2t3aJTOfT/Cr8AHGBC46zuBSq1gi5Arlzb9KjVr0hKlCVvLo9cHGH8G6QIe3TzlOEh5cNkP9YGlzJuMV04Z6yoF+OEUaz9VyiX/Z2KnallA4AZEYKtx4sDqZhpbQ3IYOycNiWrJ0csLrVi2SGTk7HajuejY=
